In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("cars.csv")

In [3]:
df

HP        MPG  VOL          SP         WT
0    49  53.700681   89  104.185353  28.762059
1    55  50.013401   92  105.461264  30.466833
2    55  50.013401   92  105.461264  30.193597
3    70  45.696322   92  113.461264  30.632114
4    53  50.504232   92  104.461264  29.889149
..  ...        ...  ...         ...        ...
76  322  36.900000   50  169.598513  16.132947
77  238  19.197888  115  150.576579  37.923113
78  263  34.000000   50  151.598513  15.769625
79  295  19.833733  119  167.944460  39.423099
80  236  12.101263  107  139.840817  34.948615

[81 rows x 5 columns]

In [4]:
df.isnull().sum()

HP     0
MPG    0
VOL    0
SP     0
WT     0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   HP      81 non-null     int64  
 1   MPG     81 non-null     float64
 2   VOL     81 non-null     int64  
 3   SP      81 non-null     float64
 4   WT      81 non-null     float64
dtypes: float64(3), int64(2)
memory usage: 3.3 KB


In [6]:
df.head()

HP        MPG  VOL          SP         WT
0  49  53.700681   89  104.185353  28.762059
1  55  50.013401   92  105.461264  30.466833
2  55  50.013401   92  105.461264  30.193597
3  70  45.696322   92  113.461264  30.632114
4  53  50.504232   92  104.461264  29.889149

In [7]:
df.columns

Index(['HP', 'MPG', 'VOL', 'SP', 'WT'], dtype='object')

In [8]:
df.shape

(81, 5)

In [9]:
X = df[['HP', 'VOL', 'SP', 'WT']]
y = df[['MPG']]

In [10]:
X.shape

(81, 4)

In [11]:
y.shape

(81, 1)

## Splitting the data

In [37]:
X_test,X_train,y_test,y_train = train_test_split(X,y,train_size=0.80,random_state=42)

In [27]:
X_train

HP  VOL          SP         WT
30   84  114  113.484609  37.042350
0    49   89  104.185353  28.762059
22   95  101  120.288996  32.675828
31   84  101  112.288996  33.234361
18   78   91  114.369293  29.929394
28   52  104   99.564907  34.483207
10   73   89  111.185353  29.363341
70  280   50  164.598513  15.823060
4    53   92  104.461264  29.889149
12   92   99  122.105055  32.813592
49  115  101  118.288996  33.458472
33  102  113  121.392639  37.573290
67  165  127  133.680223  41.573975
35   90   98  115.013085  31.911223
68  165  123  133.312342  40.472042
45  100   99  117.105055  32.621916
73  140  160  124.715241  52.997752

## Model Building

#### Linear Regression

In [38]:
reg = LinearRegression()

In [39]:
reg.fit(X_train,y_train)

LinearRegression()

In [40]:
reg.predict([[117,98,121,32]])

array([[35.83183261]])

In [38]:
reg.intercept_

array([33.31828971])

In [39]:
reg.coef_

array([[-0.18704984, -0.36276734,  0.34800776,  0.50986476]])

In [32]:
df.corr()

HP       MPG       VOL        SP        WT
HP   1.000000 -0.725038  0.077459  0.973848  0.076513
MPG -0.725038  1.000000 -0.529057 -0.687125 -0.526759
VOL  0.077459 -0.529057  1.000000  0.102170  0.999203
SP   0.973848 -0.687125  0.102170  1.000000  0.102439
WT   0.076513 -0.526759  0.999203  0.102439  1.000000

#### Model Evaluation

In [33]:
y_pred = reg.predict(X_test)

In [34]:
mean_squared_error(y_pred,y_test)

42.26270830904136

In [35]:
np.sqrt(mean_squared_error(y_pred,y_test))

6.500977488735164

## Linear Regression

In [49]:
reg = LinearRegression()
reg.fit(X_train,y_train)
y_pred = reg.predict(X_test)
mean_squared_error(y_pred,y_test)
np.sqrt(mean_squared_error(y_pred,y_test))

4.152010694880051

### KNN Regression

In [50]:
KNN = KNeighborsRegressor()
KNN.fit(X_train,y_train)
y_pred = KNN.predict(X_test)
mean_squared_error(y_pred,y_test)
np.sqrt(mean_squared_error(y_pred,y_test))

2.151078148000082

## Decision Tree Regression

In [51]:
DT = DecisionTreeRegressor()
DT.fit(X_train,y_train)
y_pred = DT.predict(X_test)
mean_squared_error(y_pred,y_test)
np.sqrt(mean_squared_error(y_pred,y_test))

2.57825306689502

## Random Forest Regression

In [52]:
RF = RandomForestRegressor()
RF.fit(X_train,y_train)
y_pred = RF.predict(X_test)
mean_squared_error(y_pred,y_test)
np.sqrt(mean_squared_error(y_pred,y_test))

1.9557346184538127