In [76]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split

In [7]:
df = pd.read_csv(r"C:\Users\91949\Dropbox\My PC (DESKTOP-PM5C4TO)\Downloads\housing_price_dataset.csv")

In [8]:
df

SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0            2126         4          1        Rural       1969  215355.283618
1            2459         3          2        Rural       1980  195014.221626
2            1860         2          1       Suburb       1970  306891.012076
3            2294         2          1        Urban       1996  206786.787153
4            2130         5          2       Suburb       2001  272436.239065
...           ...       ...        ...          ...        ...            ...
49995        1282         5          3        Rural       1975  100080.865895
49996        2854         2          2       Suburb       1988  374507.656727
49997        2979         5          3       Suburb       1962  384110.555590
49998        2596         5          2        Rural       1984  380512.685957
49999        1572         5          3        Rural       2011  221618.583218

[50000 rows x 6 columns]

In [9]:
df.isna().sum()

SquareFeet      0
Bedrooms        0
Bathrooms       0
Neighborhood    0
YearBuilt       0
Price           0
dtype: int64

In [10]:
df.duplicated().sum()

0

In [11]:
df.head(5)

SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0        2126         4          1        Rural       1969  215355.283618
1        2459         3          2        Rural       1980  195014.221626
2        1860         2          1       Suburb       1970  306891.012076
3        2294         2          1        Urban       1996  206786.787153
4        2130         5          2       Suburb       2001  272436.239065

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   SquareFeet    50000 non-null  int64  
 1   Bedrooms      50000 non-null  int64  
 2   Bathrooms     50000 non-null  int64  
 3   Neighborhood  50000 non-null  object 
 4   YearBuilt     50000 non-null  int64  
 5   Price         50000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 2.3+ MB


In [13]:
df.columns

Index(['SquareFeet', 'Bedrooms', 'Bathrooms', 'Neighborhood', 'YearBuilt',
       'Price'],
      dtype='object')

In [15]:
X = df[['SquareFeet', 'Bedrooms', 'Bathrooms', 'Neighborhood', 'YearBuilt']]
y = df[['Price']]

In [16]:
X.shape

(50000, 5)

In [17]:
y.shape

(50000, 1)

## Importing Libraries

In [55]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.linear_model import LinearRegression

## Splitting data into train and test

In [21]:
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size = 0.75,random_state = 42)

In [22]:
X_train

SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt
27434        2184         2          1        Rural       1965
13400        2437         3          2        Urban       1971
883          1166         3          3       Suburb       2003
7303         2033         5          3        Rural       1952
45124        2431         4          3       Suburb       2007
...           ...       ...        ...          ...        ...
11284        2166         5          3       Suburb       1996
44732        2463         4          1        Urban       1953
38158        2812         4          2        Urban       2010
860          2188         3          1        Urban       1979
15795        2649         5          3        Rural       1953

[37500 rows x 5 columns]

In [23]:
X_test.shape

(12500, 5)

In [46]:
pd.get_dummies(df['Neighborhood'],dtype=int)

Rural  Suburb  Urban
0          1       0      0
1          1       0      0
2          0       1      0
3          0       0      1
4          0       1      0
...      ...     ...    ...
49995      1       0      0
49996      0       1      0
49997      0       1      0
49998      1       0      0
49999      1       0      0

[50000 rows x 3 columns]

In [47]:
def encode(n):
    if n == 'Rural':
        return 1
    elif n == 'Suburb':
        return 2
    else:
        return 3    

In [60]:
df['Neighborhood'] = df['Neighborhood'].apply(encode)

In [61]:
X = df[['SquareFeet', 'Bedrooms', 'Bathrooms', 'Neighborhood', 'YearBuilt']]
y = df[['Price']]

In [62]:
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size = 0.75,random_state = 42)

In [63]:
X_train

SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt
27434        2184         2          1             1       1965
13400        2437         3          2             3       1971
883          1166         3          3             2       2003
7303         2033         5          3             1       1952
45124        2431         4          3             2       2007
...           ...       ...        ...           ...        ...
11284        2166         5          3             2       1996
44732        2463         4          1             3       1953
38158        2812         4          2             3       2010
860          2188         3          1             3       1979
15795        2649         5          3             1       1953

[37500 rows x 5 columns]

## Model Building

### Linear Regression

In [64]:
reg = LinearRegression()

In [65]:
reg.fit(X_train,y_train)

LinearRegression()

In [66]:
reg.predict([[2000,3,2,2,2000]])

array([[221450.98497759]])

In [68]:
reg.intercept_

array([-564.02620204])

In [69]:
reg.coef_

array([[ 9.93324663e+01,  5.33698463e+03,  2.98491641e+03,
         7.15679097e+02, -3.10331410e-02]])

In [71]:
df.corr()

SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt  \
SquareFeet      1.000000 -0.002638  -0.003275      0.011186   0.000482   
Bedrooms       -0.002638  1.000000   0.007405     -0.004208   0.003147   
Bathrooms      -0.003275  0.007405   1.000000      0.001613   0.003748   
Neighborhood    0.011186 -0.004208   0.001613      1.000000  -0.000174   
YearBuilt       0.000482  0.003147   0.003748     -0.000174   1.000000   
Price           0.750720  0.072624   0.028418      0.016429  -0.002288   

                 Price  
SquareFeet    0.750720  
Bedrooms      0.072624  
Bathrooms     0.028418  
Neighborhood  0.016429  
YearBuilt    -0.002288  
Price         1.000000

## Model Evaluation

In [72]:
from sklearn.metrics import mean_squared_error

In [73]:
y_pred = reg.predict(X_test)

In [74]:
mean_squared_error(y_pred,y_test)

2458471332.5340514

In [77]:
np.sqrt(mean_squared_error(y_pred,y_test))

49582.97422033143

## KNN Regression

In [79]:
from sklearn.neighbors import KNeighborsRegressor

In [ ]:
from sklearn.tree import DecisionTreeRegressor

In [ ]:
from sklearn.ensemble import RandomForestRegressor